[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
lms_proof_of_play = "GQeKyxHQGFv46z8hM5KocYa5hrUSea1hYJrDXyH41caH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"